name: trade_chart
description: A powerful Flutter chart library, currently supporting RSI Signal and MFI Signal.
version: 0.1.4
homepage: https://github.com/appsworkspace/trade_chart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
